name: Pre-Code Review Pipeline

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout wms-inventory-management repo
        uses: actions/checkout@v3

      - name: Checkout wms-main repo
        uses: actions/checkout@v3
        with:
          repository: kityk-cargo/wms-main
          path: ./wms-main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements-dev.txt

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Check formatting with black
        run: |
          black --check .

      - name: Type check with mypy
        run: |
          mypy .

      - name: Run unit tests
        run: |
          pytest tests/unit --maxfail=0 --disable-warnings

      - name: Run integration tests
        env:
          LIQUIBASE_CHANGELOG_HOST: ./wms-main/liquibase/db/changelogs
        run: |
          pytest tests/integration --maxfail=0 --disable-warnings
