name: Release Pipeline

on:
  workflow_dispatch:  # manual trigger
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release:
    # Only run if the PR was merged (not just closed)
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set build version tag
        id: tag
        run: |
          MAJOR=1
          MINOR=0
          BUILD=$(date +'%Y%m%d-%H%M')
          VERSION="${MAJOR}.${MINOR}.${BUILD}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          git tag ${VERSION}
          git push origin ${VERSION}

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/wms-inventory-management:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}/wms-inventory-management:latest

      - name: Install PyYAML
        run: |
          pip install PyYAML

      - name: Generate OpenAPI specs
        run: |
          python -c "from app.main import app; import json, yaml; spec = app.openapi(); \
          json.dump(spec, open('openapi.json','w'), indent=2); \
          yaml.dump(spec, open('openapi.yaml','w'), default_flow_style=False)"
      
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload OpenAPI spec JSON
        uses: softprops/action-gh-release@v1/upload
        with:
          asset_path: ./openapi.json
          asset_name: openapi.json
          asset_content_type: application/json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload OpenAPI spec YAML
        uses: softprops/action-gh-release@v1/upload
        with:
          asset_path: ./openapi.yaml
          asset_name: openapi.yaml
          asset_content_type: application/x-yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
